export enum EmailEnum {
    WELCOME = "WELCOME",
    LISTING_MODERATION = "LISTING_MODERATION",
    CAR_MODEL_MISSING = "CAR_MODEL_MISSING",
    VERIFY_USER = "VERIFY_USER",
    RECOVER_PASSWORD = "RECOVER_PASSWORD",
}
