export enum RegionEnum {
    VINNYTSIA = "vinnytsia",
    VOLYN = "volyn",
    DNIPROPETROVSK = "dnipropetrovsk",
    DONETSK = "donetsk",
    ZHYTOMYR = "zhytomyr",
    ZAKARPATTIA = "zakarpattia",
    ZAPORIZHZHIA = "zaporizhzhia",
    IVANO_FRANKIVSK = "ivano-frankivsk",
    KYIV = "kyiv",
    KIROVOHRAD = "kirovohrad",
    LUHANSK = "luhansk",
    LVIV = "lviv",
    MYKOLAIV = "mykolaiv",
    ODESA = "odesa",
    POLTAVA = "poltava",
    RIVNE = "rivne",
    SUMY = "sumy",
    TERNOPIL = "ternopil",
    KHARKIV = "kharkiv",
    KHERSON = "kherson",
    KHMELNYTSKYI = "khmelnytskyi",
    CHERKASY = "cherkasy",
    CHERNIVTSI = "chernivtsi",
    CHERNIHIV = "chernihiv",
    CRIMEA = "crimea",
}
