services:
  backend:
    build: .
    container_name: auto-market-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules
    restart: always

  seeder:
    build: .
    env_file:
      - .env
    command: [ "tsx", "./scripts/main-seed.ts" ]
    volumes:
      - ./backend:/app
      - node_modules:/app/node_modules

volumes:
  node_modules: