export enum EmailEnum {
    WELCOME = "WELCOME",
    LISTING_CHECK = "LISTING_CHECK",
    LISTING_CREATED = "LISTING_CREATED",
    VERIFY_USER = "VERIFY_USER",
    RECOVERY_PASSWORD = "RECOVERY_PASSWORD",
}
