export enum EmailEnum {
    WELCOME = "WELCOME",
    LISTING_CHECK = "LISTING_CHECK",
    LISTING_CREATED = "LISTING_CREATED",
    VERIFY_USER = "VERIFY_USER",
    RECOVER_PASSWORD = "RECOVER_PASSWORD",
}
