export enum PlatformPermissionEnum {
    LISTING_CREATE = "PLATFORM:LISTING:CREATE",
    LISTING_EDIT = "PLATFORM:LISTING:EDIT",
    LISTING_DELETE = "PLATFORM:LISTING:DELETE",
    USER_BAN = "PLATFORM:USER:BAN",
}
