export enum PlatformPermissionEnum {
    LISTING_CREATE = "PLATFORM:LISTING:CREATE",
    LISTING_EDIT = "PLATFORM:LISTING:EDIT",
    LISTING_DELETE = "PLATFORM:LISTING:DELETE",
    CAR_GET_MAKES = "PLATFORM:CAR_GET_MAKES",
    CAR_GET_MODELS = "PLATFORM:CAR_GET_MODELS",
    USER_BAN = "PLATFORM:USER:BAN",
    USER_ACTIVATE = "PLATFORM:USER_ACTIVATE",
}
